default:
    - api_key: "<your OpenAI API key here>"
      organization: "<your 1st organization ID>"

    - api_key: "<your OpenAI API key here>"
      organization: "<your 2nd organization ID>"


# !!!! MAKE SURE NEVER TO PLACE ACTUAL AOAI KEYS IN THIS FILE
# !!!! THE KEYS WILL BE PICKED UP FROM THE KEYVAULT
#
#
# # gpt-4-1106-preview: # only when using `model_name: gpt-4-1106-preview`
# # This has to match the model name provided in the evaluators_config / alpaca_eval_gpt4 / configs.yaml
gpt-4-0613: # only when using `model_name: gpt-4-1106-preview`  
#- "default" # this will append all the `default` configs

    - client_class: "openai.AzureOpenAI" # doesn't use the `openai.OpenAI` client class
      # the following are passed to the `AzureOpenAI` client class
      # azure_deployment: "gpt-4-1106"
      azure_deployment: "gpt-4-0613"
      api_key: tobepickedupincode
      # azure_endpoint: https://aoaipteus2dev.openai.azure.com/openai/deployments/gpt-4-1106-Preview/chat/completions?api-version=2023-07-01-preview
      azure_endpoint: https://aoaiptcaedev1.openai.azure.com/openai/deployments/gpt-4-0613/chat/completions?api-version=2023-07-01-preview
      api_version: "2023-07-01-preview"

# # only when using `model_name: gpt-4-1106-preview`  
# #- "default" # this will append all the `default` configs
# gpt-4-1106-preview:
#     - client_class: "openai.AzureOpenAI" # doesn't use the `openai.OpenAI` client class
#       # the following are passed to the `AzureOpenAI` client class
#       # azure_deployment: "gpt-4-1106"
#       azure_deployment: "gpt-4-1106-Preview"
#       api_key: tobepickedupincode
#       azure_endpoint: https://aoaipteus2dev.openai.azure.com/openai/deployments/gpt-4-1106-Preview/chat/completions?api-version=2023-07-01-preview
#       # azure_endpoint: https://aoaiptcaedev1.openai.azure.com/openai/deployments/gpt-4-0613/chat/completions?api-version=2023-07-01-preview
#       api_version: "2023-07-01-preview"

a_model_on_a_local_server:
    # don't append defaults as we are not using the openAI server => different keys and organization
    - api_key: "<some_local_api_key>"
