phi-2-5:
  prompt_template: "phi-2-5/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "microsoft/phi-2"
    model_kwargs:
      torch_dtype: "float16"
      eos_token_id: [32000,32007]
      # trust_remote_code: True
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Phi 2-5"
  link: "https://huggingface.co/microsoft/phi-2"
